app = "edunourish"
primary_region = "cdg"

[build]
  builder = "paketobuildpacks/builder:full"

[deploy]
  release_command = "npm run migrate"

[env]
  PORT = "3000"

[[services]]
  internal_port = 3000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
